FIND_PROGRAM(LEMON_EXECUTABLE lemon)

IF (LEMON_EXECUTABLE)
    SET(LEMON_FOUND TRUE)
ENDIF ()

IF (LEMON_FOUND)
    IF (NOT LEMON_FIND_QUIETLY)
        MESSAGE(STATUS "Found lemon: ${LEMON_EXECUTABLE}")
    ENDIF ()
ELSE ()
    IF (LEMON_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find lemon")
    ENDIF ()
ENDIF ()

