FIND_PROGRAM(FLEX_EXECUTABLE flex)

IF (FLEX_EXECUTABLE)
    SET(FLEX_FOUND TRUE)
ENDIF ()

IF (FLEX_FOUND)
    IF (NOT FLEX_FIND_QUIETLY)
        MESSAGE(STATUS "Found flex: ${FLEX_EXECUTABLE}")
    ENDIF ()
ELSE ()
    IF (FLEX_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find flex")
    ENDIF ()
ENDIF ()

